// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promotigo_Winners.Data;

#nullable disable

namespace Promotigo_Winners.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Promotigo_Winners.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "+44 1234 567890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "+44 1234 567891"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PhoneNumber = "+44 1234 567892"
                        },
                        new
                        {
                            Id = 4,
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            PhoneNumber = "+44 1234 567893"
                        },
                        new
                        {
                            Id = 5,
                            Email = "charlie.davis@example.com",
                            FirstName = "Charlie",
                            LastName = "Davis",
                            PhoneNumber = "+44 1234 567894"
                        },
                        new
                        {
                            Id = 6,
                            Email = "david.miller@example.com",
                            FirstName = "David",
                            LastName = "Miller",
                            PhoneNumber = "+44 1234 567895"
                        },
                        new
                        {
                            Id = 7,
                            Email = "eve.wilson@example.com",
                            FirstName = "Eve",
                            LastName = "Wilson",
                            PhoneNumber = "+44 1234 567896"
                        },
                        new
                        {
                            Id = 8,
                            Email = "frank.moore@example.com",
                            FirstName = "Frank",
                            LastName = "Moore",
                            PhoneNumber = "+44 1234 567897"
                        },
                        new
                        {
                            Id = 9,
                            Email = "grace.taylor@example.com",
                            FirstName = "Grace",
                            LastName = "Taylor",
                            PhoneNumber = "+44 1234 567898"
                        },
                        new
                        {
                            Id = 10,
                            Email = "hank.anderson@example.com",
                            FirstName = "Hank",
                            LastName = "Anderson",
                            PhoneNumber = "+44 1234 567899"
                        },
                        new
                        {
                            Id = 11,
                            Email = "ivy.thomas@example.com",
                            FirstName = "Ivy",
                            LastName = "Thomas",
                            PhoneNumber = "+44 1234 567900"
                        },
                        new
                        {
                            Id = 12,
                            Email = "jack.jackson@example.com",
                            FirstName = "Jack",
                            LastName = "Jackson",
                            PhoneNumber = "+44 1234 567901"
                        },
                        new
                        {
                            Id = 13,
                            Email = "kathy.white@example.com",
                            FirstName = "Kathy",
                            LastName = "White",
                            PhoneNumber = "+44 1234 567902"
                        },
                        new
                        {
                            Id = 14,
                            Email = "leo.harris@example.com",
                            FirstName = "Leo",
                            LastName = "Harris",
                            PhoneNumber = "+44 1234 567903"
                        },
                        new
                        {
                            Id = 15,
                            Email = "mia.clark@example.com",
                            FirstName = "Mia",
                            LastName = "Clark",
                            PhoneNumber = "+44 1234 567904"
                        },
                        new
                        {
                            Id = 16,
                            Email = "nina.lewis@example.com",
                            FirstName = "Nina",
                            LastName = "Lewis",
                            PhoneNumber = "+44 1234 567905"
                        },
                        new
                        {
                            Id = 17,
                            Email = "oscar.walker@example.com",
                            FirstName = "Oscar",
                            LastName = "Walker",
                            PhoneNumber = "+44 1234 567906"
                        },
                        new
                        {
                            Id = 18,
                            Email = "paul.hall@example.com",
                            FirstName = "Paul",
                            LastName = "Hall",
                            PhoneNumber = "+44 1234 567907"
                        },
                        new
                        {
                            Id = 19,
                            Email = "quinn.allen@example.com",
                            FirstName = "Quinn",
                            LastName = "Allen",
                            PhoneNumber = "+44 1234 567908"
                        },
                        new
                        {
                            Id = 20,
                            Email = "rose.young@example.com",
                            FirstName = "Rose",
                            LastName = "Young",
                            PhoneNumber = "+44 1234 567909"
                        },
                        new
                        {
                            Id = 21,
                            Email = "steve.king@example.com",
                            FirstName = "Steve",
                            LastName = "King",
                            PhoneNumber = "+44 1234 567910"
                        },
                        new
                        {
                            Id = 22,
                            Email = "tina.scott@example.com",
                            FirstName = "Tina",
                            LastName = "Scott",
                            PhoneNumber = "+44 1234 567911"
                        },
                        new
                        {
                            Id = 23,
                            Email = "uma.green@example.com",
                            FirstName = "Uma",
                            LastName = "Green",
                            PhoneNumber = "+44 1234 567912"
                        },
                        new
                        {
                            Id = 24,
                            Email = "victor.adams@example.com",
                            FirstName = "Victor",
                            LastName = "Adams",
                            PhoneNumber = "+44 1234 567913"
                        },
                        new
                        {
                            Id = 25,
                            Email = "wendy.baker@example.com",
                            FirstName = "Wendy",
                            LastName = "Baker",
                            PhoneNumber = "+44 1234 567914"
                        },
                        new
                        {
                            Id = 26,
                            Email = "xander.nelson@example.com",
                            FirstName = "Xander",
                            LastName = "Nelson",
                            PhoneNumber = "+44 1234 567915"
                        },
                        new
                        {
                            Id = 27,
                            Email = "yara.carter@example.com",
                            FirstName = "Yara",
                            LastName = "Carter",
                            PhoneNumber = "+44 1234 567916"
                        },
                        new
                        {
                            Id = 28,
                            Email = "zane.mitchell@example.com",
                            FirstName = "Zane",
                            LastName = "Mitchell",
                            PhoneNumber = "+44 1234 567917"
                        },
                        new
                        {
                            Id = 29,
                            Email = "amy.perez@example.com",
                            FirstName = "Amy",
                            LastName = "Perez",
                            PhoneNumber = "+44 1234 567918"
                        },
                        new
                        {
                            Id = 30,
                            Email = "brian.roberts@example.com",
                            FirstName = "Brian",
                            LastName = "Roberts",
                            PhoneNumber = "+44 1234 567919"
                        },
                        new
                        {
                            Id = 31,
                            Email = "catherine.turner@example.com",
                            FirstName = "Catherine",
                            LastName = "Turner",
                            PhoneNumber = "+44 1234 567920"
                        },
                        new
                        {
                            Id = 32,
                            Email = "daniel.phillips@example.com",
                            FirstName = "Daniel",
                            LastName = "Phillips",
                            PhoneNumber = "+44 1234 567921"
                        },
                        new
                        {
                            Id = 33,
                            Email = "elaine.campbell@example.com",
                            FirstName = "Elaine",
                            LastName = "Campbell",
                            PhoneNumber = "+44 1234 567922"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
